// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using qoden_chat.src.Database;

namespace qoden_chat.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("qoden_chat.src.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Password = "AQAAAAEAACcQAAAAENvrSDK5PYg6qzw1sQXOWs3qAyQ0/D2kZwUZr8CP1HFDRCL5JZ2zQgk8RgKV0tV1Dw==",
                            Username = "Tolstovku"
                        },
                        new
                        {
                            Id = 200,
                            Password = "AQAAAAEAACcQAAAAENvrSDK5PYg6qzw1sQXOWs3qAyQ0/D2kZwUZr8CP1HFDRCL5JZ2zQgk8RgKV0tV1Dw==",
                            Username = "Slimakanzer"
                        },
                        new
                        {
                            Id = 300,
                            Password = "AQAAAAEAACcQAAAAENvrSDK5PYg6qzw1sQXOWs3qAyQ0/D2kZwUZr8CP1HFDRCL5JZ2zQgk8RgKV0tV1Dw==",
                            Username = "Nimatora"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
